use Documentable::Search;

sub init-search($host) is export {
    my $search-generator = Documentable::Search.new(prefix => $host.config.url-prefix);
    my @items = $search-generator.generate-entries($host.registry);
    my $template-path = 'templates/search_template.js';
    my $template = slurp($template-path);
    $template = $template.subst("ITEMS", @items.join(",\n"))
            .subst("WARNING", "DO NOT EDIT generated by $?FILE:$?LINE");
    spurt 'static/js/search.js', $template;
}
