FROM ubuntu:18.04

# install nginx
RUN apt-get update -y && apt-get install -y software-properties-common && \
    add-apt-repository -y ppa:nginx/stable && apt-get update -y && apt-get install -y nginx

# deamon mode off
RUN echo "\ndaemon off;" >> /etc/nginx/nginx.conf
RUN chown -R www-data:www-data /var/lib/nginx

# expose ports
EXPOSE 10010

# add nginx conf
ADD nginx.conf /etc/nginx/nginx.conf

WORKDIR /etc/nginx

CMD ["nginx"]